---
title: tyeltech Blog
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: tylergoza@tyeltech.com
description: "Tech info blogging from beginner to advanced. Hope someone will find
  something \n of interest. \n"
baseurl: ''
url: https://blog.tyeltech.com
github_username: tylerwgoza
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
- jekyll-archives
- jekyll-assets
jekyll-archives:
  enabled:
  - categories
  - tags
  - year
  layouts:
    year: year-archive
    tag: tag-archive
    category: category-archive
